name: Deploy API Jarvis365
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Descargar Código
        uses: actions/checkout@v4

      # Este paso asegura que los archivos lleguen a la carpeta C:\API
      - name: 2. Sincronizar Archivos
        shell: pwsh
        run: |
          if (!(Test-Path "C:\API")) { New-Item -ItemType Directory -Path "C:\API" }
          Copy-Item -Path ".\*" -Destination "C:\API" -Recurse -Force
          
      # AQUÍ ESTABA EL ERROR: Solo entramos a la carpeta, no al archiv
      - name: 3. Levantar Docker
        shell: pwsh
        run: |
          cd C:\API
          docker compose up -d --build
