name: Deploy API to Windows Server

# Se ejecuta solo al hacer push a la rama main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Esta es la palabra mágica que le dice a GitHub que busque tu servidor Windows
    runs-on: self-hosted
    
    steps:
      - name: Actualizar contenedores con Docker Compose
        # Aquí le decimos qué comandos ejecutar en la consola de tu servidor
        run: |
          # 1. Cambia esta ruta por la carpeta real donde pusiste tu docker-compose.yml
          cd C:\API\docker-compose.yaml
          
          # 2. Reconstruye y actualiza las 4 instancias
          docker compose up -d --build