name: Deploy API Jarvis365
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Descargar Código
        uses: actions/checkout@v4

      - name: 2. Limpiar y Sincronizar C:\API
        shell: pwsh
        run: |
          # Intentamos crear la carpeta si no existe
          if (!(Test-Path "C:\API")) { New-Item -ItemType Directory -Path "C:\API" }
          # Copiamos todo forzando el reemplazo
          Copy-Item -Path ".\*" -Destination "C:\API" -Recurse -Force
          
      - name: 3. Docker Build local
        shell: pwsh
        run: |
          cd C:\API
          docker compose up -d --build
